### ISSUE TITLE
airCloud working ?

### ISSUE THREAD

**Issue by nlindblo** [svmironov/aircloud_ha#12]
Apologies for using this as a means of communications to other users, but I cannot find a forum or similar. I have not been able to use this i integration or the native airCloud app and getting various messaged like "unable to contact server" or time outs for the last two weeks. I want to make sure there's nothing wrong on my side and check if airCloud is working for other people and it's just me having issues ? The Hitachi airCloud service has been flakey since I got these adapters installed, but never this long. If anyone have some comments of seeing something similar would be appreciated.

I also wish there was a way to get the Hitachi cloud service out of the picture and send these commands locally, if anyone has any thoughts on this would also be appreciated.

Thanks !

**Comment by svmironov** [comment]
Hi! 
The API consists of 2 modules, REST for sending commands and a web socket for receiving status. The web socket has been unstable for a long time, but unfortunately, sending a command requires an ID that can only be extracted from the status. But at the same time, if you did not reboot, HA integration may continue to work, since device identifiers are stored in the cache but without updating state. I was unable to reverse engineer the cloud protocol because it runs over HTTPS. Typically, the air conditioner board has several connectors for connecting external thermostats operating using the “dry contact” method or using a special protocol. Using these connectors is the only way to control without the cloud. A description of the control device can be found here https://hackaday.io/project/179797/logs. There is a discussion thread on the HA community forum, but there are almost no messages there https://community.home-assistant.io/t/hitachi-hvac-ducted-ac-integration/349449/16

**Comment by nlindblo** [comment]
So, I actually got an email response from Hitachi saying they resolved their problems and I have managed to re-pair my units and it looks like it's a bit snappier now to respond. However, after deploying some termperature meters in my house, I can see that the temperature showing from the Aircon units is vastly off the real temperature (like 2-3 degrees), would it be possible to plug a different current temperature source into the climate card than the built in one in the aircon unit ?

**Comment by nlindblo** [comment]
I looked at that but I am not sure how I would create a Heating/Cooling switch to turn on/off the Aircon's with a static temperature to let this generic thermostat manage the temperature. Have you got any suggestions how I would go about with this ?

**Comment by svmironov** [comment]
I will add the temperature correction value to the configuration in a few days

**Comment by svmironov** [comment]
I added the parameter for adjustment a current temperature.
It should be in your config.yml:
` air_cloud:
        email: "login" #supported only email authorization
        password: "pass"
        temp_adjust: -1 #optional parameter for adjustment current tem`
