### ISSUE TITLE
Update HA

### ISSUE THREAD

**Issue by IncognitoMSK** [svmironov/aircloud_ha#6]
After updating to

Home Assistant 2023.6.0
Supervisor 2023.06.1
Operating System 10.2

integration is broken ((((

**Comment by calebgab** [comment]
@IncognitoMSK - I saw this error early when you posted it and so delayed upgrading HA as I didn't want to break my AirCloud integration but it broke last week sometime and I just got around to looking at it. I was running Home Assistant 2023.5.6, Supervisior 2023.06.4 and Operating System 10.3. I was getting very similar errors as you, but all referencing phython3.10. However, after upgrading to Home Assistant 2023.6.3, my integration is now working again and I'm not getting any of those errors. Have you upgraded since your post?

**Comment by svmironov** [comment]
Sorry for late response. I tested integration with all latest versions HA and it works. Errors in log can be bad internet connection or unstable API
